apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: zero-balance-alert-manager-config
  labels:
    release: prometheus
spec:
    route:
      groupBy: ['job', 'alertname']
      groupWait: 30s
      groupInterval: 1m
      repeatInterval: 2m
      receiver: 'email-receiver'
      matchers:
      - name: severity
        value: critical
      - name: alertname
        value: Zerobalance

    receivers:
    - name: 'email-receiver'
      emailConfigs:
      - from: 'alerts@example.com'
        smarthost: 'mailhog:1025'
        to: 'user@example.com'
        requireTLS: false
